# Generated by Django 4.2.4 on 2023-08-22 05:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintBindingTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=150, verbose_name="name"),
                ),
                ("photo", models.FileField(upload_to="binding/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Тип переплета печати",
                "verbose_name_plural": "Типы переплета печати",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "printSize",
                    models.IntegerField(choices=[(1, "A4"), (2, "A5")], default=1),
                ),
                (
                    "bookCover",
                    models.IntegerField(
                        choices=[(1, "Мягкий"), (2, "Твердый"), (3, "Пластиковый ")],
                        default=1,
                    ),
                ),
                (
                    "printColor",
                    models.IntegerField(
                        choices=[(1, "Черно-белый"), (2, "Цветной")], default=1
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_status", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "printBindingType",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="printBindingTypes",
                        to="products.printbindingtypes",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
            managers=[
                ("productListByUser", django.db.models.manager.Manager()),
            ],
        ),
    ]
